var redditData = {
"kind": "Listing",
"data": {
"modhash": "op5pp9gc3e6679b5c0e44b09e0a6efb7a52373711afa76f03b",
"children": [
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;It&amp;#39;s really helpful and reduces the need to put tourist site suggestion requests on the subreddit feed&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "It's really helpful and reduces the need to put tourist site suggestion requests on the subreddit feed",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v9r2t",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "swampfox20",
"num_comments": 1,
"score": 25,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": true,
"is_self": true,
"permalink": "/r/Charleston/comments/2v9r2t/tourists_please_read_sidebar_for_site_suggestions/",
"name": "t3_2v9r2t",
"created": 1423487346,
"url": "http://www.reddit.com/r/Charleston/comments/2v9r2t/tourists_please_read_sidebar_for_site_suggestions/",
"author_flair_text": null,
"title": "Tourists Please Read Sidebar for Site Suggestions",
"created_utc": 1423458546,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 25
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;&lt;a href=\"https://www.facebook.com/pages/Charleston-Cars-Coffee/198336256874223\"&gt;Cars and Coffee&lt;/a&gt;&lt;/p&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;A bunch of car and motorcycle enthusiasts that meet up every Saturday around 8AM at the MTP Towne Centre in front of Atlanta Bread Company.&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;p&gt;I went to one over the summer and it was a pretty good turn out.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "[Cars and Coffee](https://www.facebook.com/pages/Charleston-Cars-Coffee/198336256874223)\n\n&gt;A bunch of car and motorcycle enthusiasts that meet up every Saturday around 8AM at the MTP Towne Centre in front of Atlanta Bread Company.\n\nI went to one over the summer and it was a pretty good turn out.",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vjfjo",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "mr_william",
"num_comments": 7,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vjfjo/any_car_guys_or_gals_on_here_anyone_want_to_meet/",
"name": "t3_2vjfjo",
"created": 1423694919,
"url": "http://www.reddit.com/r/Charleston/comments/2vjfjo/any_car_guys_or_gals_on_here_anyone_want_to_meet/",
"author_flair_text": null,
"title": "Any car guys or gals on here? Anyone want to meet up at Cars and Coffee in MtP on Saturday morning?",
"created_utc": 1423666119,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Do you like to have fun?&lt;/p&gt;\n\n&lt;p&gt;Do you want to play a sport you never heard of?&lt;/p&gt;\n\n&lt;p&gt;Do you like going to shitty bars and drinking with great people? &lt;/p&gt;\n\n&lt;p&gt;Are you a parent that would like to meet other parents with young children? &lt;/p&gt;\n\n&lt;p&gt;Are you still reading this?&lt;/p&gt;\n\n&lt;p&gt;If you answered yes to any of these questions the Charleston Hurling Club is for you! (&lt;a href=\"http://charlestonhurling.com/\"&gt;http://charlestonhurling.com/&lt;/a&gt;) We are currently recruiting both males and females for the spring league and tournament season. The club has been growing exponentially and a good number of our players started last year with no prior experience. We currently have 3 Coed teams but are hoping to expand to at least four Coed teams and one Camogie (female hurling) team. &lt;/p&gt;\n\n&lt;p&gt;The Club was nominated for the one of the five top local sports by &lt;a href=\"http://charlestoncitypaper.secondstreetapp.com/l/Best-of-...\"&gt;Charleston City Paper &lt;/a&gt;. Unlike every other league on the list you can come join this team! &lt;/p&gt;\n\n&lt;p&gt;So I started with the club last year and it has been awesome! The first day there everyone greeted me and the main guy (straight from Ireland) spent an hour of his time teaching me the basics. That day they invited me to eat with them afterward. The next time I showed up they invited me to a bar afterward, bought all the beer, and we all talked like we were old friends. The third time I showed up, my family (wife, 2 year old, and 10 month old) and I were invited to a house party with everyone and their families. I really have never meet a nicer and more accepting group. I would like to return their generosity by recruiting more people (that&amp;#39;s where you come in.) There are no fees until you decide to join the league/tournaments , the club has equipment you can use, you may get free beer out of it, and you will meet a great group of people. &lt;/p&gt;\n\n&lt;p&gt;Practice start at Hampton Park soccer fields (Moultrie St and Rutledge) Sunday February 15th @10am. After the time changes Wednesday practice start up at @6pm. &lt;/p&gt;\n\n&lt;p&gt;League starts in March. &lt;/p&gt;\n\n&lt;p&gt;PM me if you are interested or you are welcome to just show up to a practice and introduce yourself.&lt;/p&gt;\n\n&lt;p&gt;Wear athletic gear. Cleats are preferred but not required.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Do you like to have fun?\n\nDo you want to play a sport you never heard of?\n\nDo you like going to shitty bars and drinking with great people? \n\nAre you a parent that would like to meet other parents with young children? \n\nAre you still reading this?\n\nIf you answered yes to any of these questions the Charleston Hurling Club is for you! (http://charlestonhurling.com/) We are currently recruiting both males and females for the spring league and tournament season. The club has been growing exponentially and a good number of our players started last year with no prior experience. We currently have 3 Coed teams but are hoping to expand to at least four Coed teams and one Camogie (female hurling) team. \n\nThe Club was nominated for the one of the five top local sports by [Charleston City Paper ](http://charlestoncitypaper.secondstreetapp.com/l/Best-of-...). Unlike every other league on the list you can come join this team! \n\nSo I started with the club last year and it has been awesome! The first day there everyone greeted me and the main guy (straight from Ireland) spent an hour of his time teaching me the basics. That day they invited me to eat with them afterward. The next time I showed up they invited me to a bar afterward, bought all the beer, and we all talked like we were old friends. The third time I showed up, my family (wife, 2 year old, and 10 month old) and I were invited to a house party with everyone and their families. I really have never meet a nicer and more accepting group. I would like to return their generosity by recruiting more people (that's where you come in.) There are no fees until you decide to join the league/tournaments , the club has equipment you can use, you may get free beer out of it, and you will meet a great group of people. \n\nPractice start at Hampton Park soccer fields (Moultrie St and Rutledge) Sunday February 15th @10am. After the time changes Wednesday practice start up at @6pm. \n\nLeague starts in March. \n\nPM me if you are interested or you are welcome to just show up to a practice and introduce yourself.\n\nWear athletic gear. Cleats are preferred but not required.",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vhny8",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "MURRT",
"num_comments": 2,
"score": 6,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vhny8/lots_of_fun_with_a_great_group_of_people_and_a/",
"name": "t3_2vhny8",
"created": 1423649916,
"url": "http://www.reddit.com/r/Charleston/comments/2vhny8/lots_of_fun_with_a_great_group_of_people_and_a/",
"author_flair_text": null,
"title": "Lots of fun with a great group of people and a 3000 year old sport!",
"created_utc": 1423621116,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 6
}
},
{
"kind": "t3",
"data": {
"domain": "abcnews4.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vfoyd",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "hjwoolwine",
"num_comments": 25,
"score": 26,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://b.thumbs.redditmedia.com/kTt9DjutD8mrZgWX2kLsviXd8CIT-XrHRXnptpEUTxQ.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": false,
"permalink": "/r/Charleston/comments/2vfoyd/whats_going_on_bomb_threat_at_coc_nothing_found/",
"name": "t3_2vfoyd",
"created": 1423617956,
"url": "http://www.abcnews4.com/story/28071356/dispatch-crews-respond-to-bomb-threat-near-cofc-campus",
"author_flair_text": null,
"title": "What's going on? Bomb threat at CoC. Nothing found, but still being treated as a threat.",
"created_utc": 1423589156,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 26
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Wanna dance to some sick beats. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Wanna dance to some sick beats. ",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vi34v",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "lghollings",
"num_comments": 3,
"score": 1,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vi34v/best_place_for_house_and_techno_music/",
"name": "t3_2vi34v",
"created": 1423657518,
"url": "http://www.reddit.com/r/Charleston/comments/2vi34v/best_place_for_house_and_techno_music/",
"author_flair_text": null,
"title": "Best place for house and techno music?",
"created_utc": 1423628718,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 1
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;This time, they&amp;#39;re saying they want to increase rates, which will in the end help lower rates (wink wink)...    I&amp;#39;m not sure there is another monopoly like this, that can force their clients to pay for what would otherwise just be &amp;quot;the cost of doing business&amp;quot;.  &lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"http://www.postandcourier.com/article/20150210/PC05/150219944/1177/sceg-announces-proposed-solar-initiatives-rate-increase\"&gt;http://www.postandcourier.com/article/20150210/PC05/150219944/1177/sceg-announces-proposed-solar-initiatives-rate-increase&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "This time, they're saying they want to increase rates, which will in the end help lower rates (wink wink)...    I'm not sure there is another monopoly like this, that can force their clients to pay for what would otherwise just be \"the cost of doing business\".  \n\nhttp://www.postandcourier.com/article/20150210/PC05/150219944/1177/sceg-announces-proposed-solar-initiatives-rate-increase",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vgltu",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "wisertime07",
"num_comments": 6,
"score": 8,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vgltu/surprise_sceg_wants_another_rate_increase/",
"name": "t3_2vgltu",
"created": 1423632484,
"url": "http://www.reddit.com/r/Charleston/comments/2vgltu/surprise_sceg_wants_another_rate_increase/",
"author_flair_text": null,
"title": "Surprise! SCE&amp;G wants another rate increase...",
"created_utc": 1423603684,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 8
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I live in Maryland and have been helping a local soldier try to locate his German Shepherd. The short version is that his sitter claimed Zara ran away here in Maryland. Just a couple weeks before he was coming home from deployment. I cannot even telk you how many man hours were spent searching here. &lt;/p&gt;\n\n&lt;p&gt;Many believed the sitter was involved but police would not get involved (i do not know the particulars of why other then somerhing about a civil case). He never gave up  He now has evidence the dog is in the greenville/spartansburg area of SC. He has a facebook page set up &amp;quot;Help Bring zara&amp;quot; Home&amp;quot; and will be posting the evidence tonight when he gets off work.&lt;/p&gt;\n\n&lt;p&gt;He has asked all the followers to spread the info far and wide down there. I guess I am asking if anyone down that way, or with connections there, can keep an eye on his FB page for the info to come tonight and spread it like wildfire. Lets bring Zara home.&lt;/p&gt;\n\n&lt;p&gt;Thanks.&lt;/p&gt;\n\n&lt;p&gt;Edit&amp;quot; spelling&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I live in Maryland and have been helping a local soldier try to locate his German Shepherd. The short version is that his sitter claimed Zara ran away here in Maryland. Just a couple weeks before he was coming home from deployment. I cannot even telk you how many man hours were spent searching here. \n\nMany believed the sitter was involved but police would not get involved (i do not know the particulars of why other then somerhing about a civil case). He never gave up  He now has evidence the dog is in the greenville/spartansburg area of SC. He has a facebook page set up \"Help Bring zara\" Home\" and will be posting the evidence tonight when he gets off work.\n\nHe has asked all the followers to spread the info far and wide down there. I guess I am asking if anyone down that way, or with connections there, can keep an eye on his FB page for the info to come tonight and spread it like wildfire. Lets bring Zara home.\n\nThanks.\n\nEdit\" spelling",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vgrrc",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "techiegirl74",
"num_comments": 0,
"score": 4,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": 1423607382,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vgrrc/please_help_find_a_soldiers_stolen_dog/",
"name": "t3_2vgrrc",
"created": 1423634974,
"url": "http://www.reddit.com/r/Charleston/comments/2vgrrc/please_help_find_a_soldiers_stolen_dog/",
"author_flair_text": null,
"title": "Please!! Help find a soldiers stolen dog",
"created_utc": 1423606174,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 4
}
},
{
"kind": "t3",
"data": {
"domain": "vimeo.com",
"banned_by": null,
"media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F119224548&amp;src_secure=1&amp;url=http%3A%2F%2Fvimeo.com%2F119224548&amp;image=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F506401918_1280.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=vimeo\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 338
},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"user_reports": [],
"secure_media": {
"oembed": {
"provider_url": "https://vimeo.com/",
"description": "Throw Charleston heads down King street for some Second Sunday activities. Featuring Ryan Sanders on the yoyo.",
"title": "Throw Charleston - Second Sunday",
"type": "video",
"thumbnail_width": 1280,
"height": 338,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F119224548&amp;url=http%3A%2F%2Fvimeo.com%2F119224548&amp;image=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F506401918_1280.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=vimeo\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"author_name": "Poon and Friends",
"version": "1.0",
"provider_name": "Vimeo",
"thumbnail_url": "https://i.embed.ly/1/image?url=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F506401918_1280.jpg&amp;key=b1e305db91cf4aa5a86b732cc9fffceb",
"thumbnail_height": 720,
"author_url": "http://vimeo.com/poonandfriends"
},
"type": "vimeo.com"
},
"link_flair_text": null,
"id": "2vg67e",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "WinstonPoonPhoenix",
"num_comments": 1,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://a.thumbs.redditmedia.com/1V6LUX4AaOSJSxIxXERMlYdNs2VFS2AvQnZqFuhn480.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F119224548&amp;url=http%3A%2F%2Fvimeo.com%2F119224548&amp;image=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F506401918_1280.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=vimeo\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 338
},
"saved": false,
"stickied": false,
"is_self": false,
"permalink": "/r/Charleston/comments/2vg67e/throw_charleston_second_sunday_ft_ryan_sanders/",
"name": "t3_2vg67e",
"created": 1423625782,
"url": "https://vimeo.com/119224548",
"author_flair_text": null,
"title": "Throw Charleston - Second Sunday ft. Ryan Sanders",
"created_utc": 1423596982,
"distinguished": null,
"media": {
"oembed": {
"provider_url": "https://vimeo.com/",
"description": "Throw Charleston heads down King street for some Second Sunday activities. Featuring Ryan Sanders on the yoyo.",
"title": "Throw Charleston - Second Sunday",
"type": "video",
"thumbnail_width": 1280,
"height": 338,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F119224548&amp;src_secure=1&amp;url=http%3A%2F%2Fvimeo.com%2F119224548&amp;image=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F506401918_1280.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=vimeo\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"author_name": "Poon and Friends",
"version": "1.0",
"provider_name": "Vimeo",
"thumbnail_url": "http://i.vimeocdn.com/video/506401918_1280.jpg",
"thumbnail_height": 720,
"author_url": "http://vimeo.com/poonandfriends"
},
"type": "vimeo.com"
},
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Do you like to drink? Do you like to run/walk? Do you like to sing possibly offensive songs? If you answered yes to 1 or more of these questions the Charleston Happy Heretics might be for you! We are Hash House Harriers, a group that was started in 1939 in Malaysia. The basics are that we meet up, a Hare sets a trail, the pack follows that trail. There are no winners, there are no losers only beer.....lots and lots of beer. We drink before, during and after trail. The good news is we are running Saturday on Folly Beach!!!!! If you want to join us PM me or follow this link &lt;a href=\"http://www.meetup.com/Happyheretics/\"&gt;http://www.meetup.com/Happyheretics/&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Do you like to drink? Do you like to run/walk? Do you like to sing possibly offensive songs? If you answered yes to 1 or more of these questions the Charleston Happy Heretics might be for you! We are Hash House Harriers, a group that was started in 1939 in Malaysia. The basics are that we meet up, a Hare sets a trail, the pack follows that trail. There are no winners, there are no losers only beer.....lots and lots of beer. We drink before, during and after trail. The good news is we are running Saturday on Folly Beach!!!!! If you want to join us PM me or follow this link http://www.meetup.com/Happyheretics/",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vfbfo",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "ayoungad",
"num_comments": 5,
"score": 9,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vfbfo/drinking_club_with_a_running_problem/",
"name": "t3_2vfbfo",
"created": 1423611708,
"url": "http://www.reddit.com/r/Charleston/comments/2vfbfo/drinking_club_with_a_running_problem/",
"author_flair_text": null,
"title": "Drinking Club with a running problem",
"created_utc": 1423582908,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 9
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Can anyone recommend a good four wheeler mechanic in the Charleston area? Thanks in advance&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Can anyone recommend a good four wheeler mechanic in the Charleston area? Thanks in advance",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vfjkk",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "rushchaser",
"num_comments": 2,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vfjkk/good_four_wheeler_mechanic_in_charleston_area/",
"name": "t3_2vfjkk",
"created": 1423615566,
"url": "http://www.reddit.com/r/Charleston/comments/2vfjkk/good_four_wheeler_mechanic_in_charleston_area/",
"author_flair_text": null,
"title": "Good Four Wheeler Mechanic in Charleston area",
"created_utc": 1423586766,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 3
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;So I&amp;#39;ve been in Charleston for about a year and there&amp;#39;s some amazing beer bars with tons of options.  But it seems that no one in this town has a $2.00 pint night or anything of the like.  Aside from finding a $2 Bud Light special no one seems to sell decent beer for anything less than $4 a piece.  I feel like every town has a few places that run some good weekday specials but I haven&amp;#39;t been able to find them here. Any suggestions?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "So I've been in Charleston for about a year and there's some amazing beer bars with tons of options.  But it seems that no one in this town has a $2.00 pint night or anything of the like.  Aside from finding a $2 Bud Light special no one seems to sell decent beer for anything less than $4 a piece.  I feel like every town has a few places that run some good weekday specials but I haven't been able to find them here. Any suggestions?",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vc02t",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "AberdeenWashington",
"num_comments": 15,
"score": 18,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vc02t/cheap_beer/",
"name": "t3_2vc02t",
"created": 1423540417,
"url": "http://www.reddit.com/r/Charleston/comments/2vc02t/cheap_beer/",
"author_flair_text": null,
"title": "Cheap beer?",
"created_utc": 1423511617,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 18
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I blew a head gasket in my car, and it&amp;#39;s beat to shit as well, translation, I haven&amp;#39;t even been able to sell it for $500. I&amp;#39;m moving out of town next week, so just want to sell it to a junk yard or wherever will give me a few hundred bucks for it. Does anyone have any advice on the best place to get cash out of it? I&amp;#39;m in West Ashley, but can have AAA tow it elsewhere if necessary. Bonus points if there is a place that will pick it up and buy it from me then. Thanks.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I blew a head gasket in my car, and it's beat to shit as well, translation, I haven't even been able to sell it for $500. I'm moving out of town next week, so just want to sell it to a junk yard or wherever will give me a few hundred bucks for it. Does anyone have any advice on the best place to get cash out of it? I'm in West Ashley, but can have AAA tow it elsewhere if necessary. Bonus points if there is a place that will pick it up and buy it from me then. Thanks.",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vd8ye",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "VeiledAiel",
"num_comments": 9,
"score": 6,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vd8ye/scrapping_my_car/",
"name": "t3_2vd8ye",
"created": 1423560551,
"url": "http://www.reddit.com/r/Charleston/comments/2vd8ye/scrapping_my_car/",
"author_flair_text": null,
"title": "Scrapping my car",
"created_utc": 1423531751,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 6
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I finally have the means to get myself a car, and now I can&amp;#39;t seem to find anything reasonable within my budget. Can anyone suggest any half-decent lots for used cars? My limit is $2500. Craigslist and auto trader don&amp;#39;t seem to have much. I&amp;#39;m hoping to find a good 4 door vehicle so I can get my kids in and out easily enough. Thank you all for any input.  (Also, I&amp;#39;m in the Goose Creek/Summerville area if that helps)&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I finally have the means to get myself a car, and now I can't seem to find anything reasonable within my budget. Can anyone suggest any half-decent lots for used cars? My limit is $2500. Craigslist and auto trader don't seem to have much. I'm hoping to find a good 4 door vehicle so I can get my kids in and out easily enough. Thank you all for any input.  (Also, I'm in the Goose Creek/Summerville area if that helps)",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vclop",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "RayvenRayge",
"num_comments": 11,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2vclop/used_car_shopping/",
"name": "t3_2vclop",
"created": 1423549671,
"url": "http://www.reddit.com/r/Charleston/comments/2vclop/used_car_shopping/",
"author_flair_text": null,
"title": "Used Car Shopping",
"created_utc": 1423520871,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "bacechs.org",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2vapy4",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "patriche",
"num_comments": 13,
"score": 17,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://b.thumbs.redditmedia.com/QR54dCa3wbAidYdInUdhiD-FumZNZ38G9W4O-bz2BrM.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": false,
"permalink": "/r/Charleston/comments/2vapy4/public_listening_session_moratorium_on_new_bars/",
"name": "t3_2vapy4",
"created": 1423517433,
"url": "http://www.bacechs.org/lnar-updates/",
"author_flair_text": null,
"title": "Public listening session - Moratorium on new bars being allowed to stay open after midnight",
"created_utc": 1423488633,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 17
}
},
{
"kind": "t3",
"data": {
"domain": "youtu.be",
"banned_by": null,
"media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fwww.youtube.com%2Fembed%2FcuwBWRx6jj4%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DcuwBWRx6jj4&amp;image=http%3A%2F%2Fi.ytimg.com%2Fvi%2FcuwBWRx6jj4%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 338
},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"user_reports": [],
"secure_media": {
"oembed": {
"provider_url": "http://www.youtube.com/",
"description": "Day trip to Botany Bay Plantation in Edisto Beach, South Carolina from Charleston, South Carolina. Spent the whole day digging through shells on Boneyard Beach. Definitely worth the trip if you live nearby or if you're ever visiting Charleston or the surrounding islands.",
"title": "Botany Bay",
"url": "http://www.youtube.com/watch?v=cuwBWRx6jj4",
"type": "video",
"author_name": "Chris White",
"height": 338,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FcuwBWRx6jj4%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DcuwBWRx6jj4&amp;image=http%3A%2F%2Fi.ytimg.com%2Fvi%2FcuwBWRx6jj4%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"thumbnail_width": 480,
"version": "1.0",
"provider_name": "YouTube",
"thumbnail_url": "https://i.embed.ly/1/image?url=http%3A%2F%2Fi.ytimg.com%2Fvi%2FcuwBWRx6jj4%2Fhqdefault.jpg&amp;key=b1e305db91cf4aa5a86b732cc9fffceb",
"thumbnail_height": 360,
"author_url": "http://www.youtube.com/user/chrislovessushi"
},
"type": "youtu.be"
},
"link_flair_text": null,
"id": "2v75mm",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "chrislovessushi",
"num_comments": 2,
"score": 15,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://b.thumbs.redditmedia.com/zXJGwWnD0_mLthy0gP3eblnOzdVB7aeu60U3Do7kXms.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FcuwBWRx6jj4%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DcuwBWRx6jj4&amp;image=http%3A%2F%2Fi.ytimg.com%2Fvi%2FcuwBWRx6jj4%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 338
},
"saved": false,
"stickied": false,
"is_self": false,
"permalink": "/r/Charleston/comments/2v75mm/shot_this_at_botany_bay_boneyard_beach_yesterday/",
"name": "t3_2v75mm",
"created": 1423439255,
"url": "http://youtu.be/cuwBWRx6jj4",
"author_flair_text": null,
"title": "Shot this at Botany Bay / Boneyard Beach yesterday. You must go!",
"created_utc": 1423410455,
"distinguished": null,
"media": {
"oembed": {
"provider_url": "http://www.youtube.com/",
"description": "Day trip to Botany Bay Plantation in Edisto Beach, South Carolina from Charleston, South Carolina. Spent the whole day digging through shells on Boneyard Beach. Definitely worth the trip if you live nearby or if you're ever visiting Charleston or the surrounding islands.",
"title": "Botany Bay",
"url": "http://www.youtube.com/watch?v=cuwBWRx6jj4",
"type": "video",
"author_name": "Chris White",
"height": 338,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fwww.youtube.com%2Fembed%2FcuwBWRx6jj4%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DcuwBWRx6jj4&amp;image=http%3A%2F%2Fi.ytimg.com%2Fvi%2FcuwBWRx6jj4%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"thumbnail_width": 480,
"version": "1.0",
"provider_name": "YouTube",
"thumbnail_url": "http://i.ytimg.com/vi/cuwBWRx6jj4/hqdefault.jpg",
"thumbnail_height": 360,
"author_url": "http://www.youtube.com/user/chrislovessushi"
},
"type": "youtu.be"
},
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 15
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;What&amp;#39;s up &lt;a href=\"/r/Charleston\"&gt;/r/Charleston&lt;/a&gt;!  My wife and I are in the middle of a sightseeing weekend binge where we go to different cities that are on the potential move-to list.  Charleston is in our top five so we decided to make this a longer weekend and will be in the area next Friday - Monday.  Current plans are to hit up Boone Hall Plantation and Irvin House Vineyards but I figured I&amp;#39;d ask you fine people to get any suggestions.  We&amp;#39;re in our late 20&amp;#39;s/early 30&amp;#39;s, no kids (yet), and are game for pretty much anything that will give us a sense for what it&amp;#39;s like to actually live in this fine town of yours. &lt;/p&gt;\n\n&lt;p&gt;So if you were to suggest things to do to get a true sense of Charleston as someone who wants to live there - what would you do/see?  Thanks everyone!&lt;/p&gt;\n\n&lt;p&gt;Mods - if I&amp;#39;m breaking any rules here or this is a common repost please just let me know!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "What's up /r/Charleston!  My wife and I are in the middle of a sightseeing weekend binge where we go to different cities that are on the potential move-to list.  Charleston is in our top five so we decided to make this a longer weekend and will be in the area next Friday - Monday.  Current plans are to hit up Boone Hall Plantation and Irvin House Vineyards but I figured I'd ask you fine people to get any suggestions.  We're in our late 20's/early 30's, no kids (yet), and are game for pretty much anything that will give us a sense for what it's like to actually live in this fine town of yours. \n\n\nSo if you were to suggest things to do to get a true sense of Charleston as someone who wants to live there - what would you do/see?  Thanks everyone!\n\n\nMods - if I'm breaking any rules here or this is a common repost please just let me know!",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v91ki",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "geeked0ut",
"num_comments": 19,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v91ki/thinking_of_moving_to_charleston_any_suggestions/",
"name": "t3_2v91ki",
"created": 1423473371,
"url": "http://www.reddit.com/r/Charleston/comments/2v91ki/thinking_of_moving_to_charleston_any_suggestions/",
"author_flair_text": null,
"title": "Thinking of moving to Charleston, any suggestions for next weekend (2/13-2/16)?",
"created_utc": 1423444571,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 0
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v6gt5",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "SmashBros4",
"num_comments": 17,
"score": 8,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v6gt5/any_smashers/",
"name": "t3_2v6gt5",
"created": 1423415637,
"url": "http://www.reddit.com/r/Charleston/comments/2v6gt5/any_smashers/",
"author_flair_text": null,
"title": "Any Smashers?",
"created_utc": 1423386837,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 8
}
},
{
"kind": "t3",
"data": {
"domain": "imgur.com",
"banned_by": null,
"media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fimgur.com%2Fa%2FqhMhN%2Fembed&amp;url=http%3A%2F%2Fimgur.com%2Fa%2FqhMhN&amp;image=http%3A%2F%2Fi.imgur.com%2FSrxVuGC.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=imgur\" width=\"550\" height=\"550\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 550,
"scrolling": false,
"height": 550
},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v5fzm",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "the-mp",
"num_comments": 4,
"score": 18,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://a.thumbs.redditmedia.com/Kx4U560xNejKqoS4_U05gfkfcAC-9s5aojZNwsHNqQ4.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": false,
"permalink": "/r/Charleston/comments/2v5fzm/santee_coastal_preserve_30_min_outside_charleston/",
"name": "t3_2v5fzm",
"created": 1423389102,
"url": "http://imgur.com/a/qhMhN",
"author_flair_text": null,
"title": "Santee Coastal Preserve, 30 min outside Charleston, is beautiful. [x/ southcarolina]",
"created_utc": 1423360302,
"distinguished": null,
"media": {
"type": "imgur.com",
"oembed": {
"provider_url": "http://imgur.com",
"version": "1.0",
"title": "Santee Coastal - Feb 15",
"thumbnail_width": 4000,
"height": 550,
"width": 550,
"html": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fimgur.com%2Fa%2FqhMhN%2Fembed&amp;url=http%3A%2F%2Fimgur.com%2Fa%2FqhMhN&amp;image=http%3A%2F%2Fi.imgur.com%2FSrxVuGC.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=imgur\" width=\"550\" height=\"550\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"provider_name": "Imgur",
"thumbnail_url": "http://i.imgur.com/SrxVuGC.jpg",
"type": "rich",
"thumbnail_height": 3000
}
},
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 18
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I have lived in the Charleston area area for a few years now and I am looking for a great place to get a philly cheese steak. &lt;/p&gt;\n\n&lt;p&gt;I would not mind driving to find a good one so any place in Charleston / Berkeley County to try it out. &lt;/p&gt;\n\n&lt;p&gt;Thanks in advance.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I have lived in the Charleston area area for a few years now and I am looking for a great place to get a philly cheese steak. \n\nI would not mind driving to find a good one so any place in Charleston / Berkeley County to try it out. \n\nThanks in advance.",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v5c6r",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "airpilk",
"num_comments": 16,
"score": 10,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v5c6r/place_to_get_a_good_philly_cheese_steak/",
"name": "t3_2v5c6r",
"created": 1423387022,
"url": "http://www.reddit.com/r/Charleston/comments/2v5c6r/place_to_get_a_good_philly_cheese_steak/",
"author_flair_text": null,
"title": "Place to get a good philly cheese steak?",
"created_utc": 1423358222,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 10
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;My girlfriend and I are always looking for other casual board gamers in the area.  We mainly stick with games that we can play while hanging out/partying/drunk, we&amp;#39;ve got...&lt;/p&gt;\n\n&lt;p&gt;Carcassonne, Alhambra, Ticket to Ride Europe, Small World, Takenoko, Splendor, Cards Against Humanity, Rampage, Castle Panic, Pandemic, Munchkin, Tsuro of the Seas, Forbidden Island, Love Letter, Fluxx, Gloom, and Get Bit&lt;/p&gt;\n\n&lt;p&gt;We used to make it over to Frothy Beard&amp;#39;s Game Night every Thursday night but lately we&amp;#39;ve only been making it out there once a month or so.&lt;/p&gt;\n\n&lt;p&gt;Anybody?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "My girlfriend and I are always looking for other casual board gamers in the area.  We mainly stick with games that we can play while hanging out/partying/drunk, we've got...\n\nCarcassonne, Alhambra, Ticket to Ride Europe, Small World, Takenoko, Splendor, Cards Against Humanity, Rampage, Castle Panic, Pandemic, Munchkin, Tsuro of the Seas, Forbidden Island, Love Letter, Fluxx, Gloom, and Get Bit\n\nWe used to make it over to Frothy Beard's Game Night every Thursday night but lately we've only been making it out there once a month or so.\n\nAnybody?",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v4f8p",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "TheCiotti",
"num_comments": 7,
"score": 11,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v4f8p/any_casual_board_gamers_out_there/",
"name": "t3_2v4f8p",
"created": 1423340724,
"url": "http://www.reddit.com/r/Charleston/comments/2v4f8p/any_casual_board_gamers_out_there/",
"author_flair_text": null,
"title": "Any Casual Board Gamers Out There???",
"created_utc": 1423340724,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 11
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I just need to get some pants hemmed, but I want to find someone who does good work for a reasonable price.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I just need to get some pants hemmed, but I want to find someone who does good work for a reasonable price.",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v4pio",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "aj67890",
"num_comments": 6,
"score": 4,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v4pio/can_anyone_recommend_a_tailor/",
"name": "t3_2v4pio",
"created": 1423374896,
"url": "http://www.reddit.com/r/Charleston/comments/2v4pio/can_anyone_recommend_a_tailor/",
"author_flair_text": null,
"title": "Can anyone recommend a tailor?",
"created_utc": 1423346096,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 4
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v3pdt",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "ooeygooeywomb",
"num_comments": 10,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v3pdt/best_bloody_marybrunch_spot/",
"name": "t3_2v3pdt",
"created": 1423356522,
"url": "http://www.reddit.com/r/Charleston/comments/2v3pdt/best_bloody_marybrunch_spot/",
"author_flair_text": null,
"title": "Best bloody mary/brunch spot?",
"created_utc": 1423327722,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 3
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I moved here about a week ago and would like to teach my girlfriend the joy of fishing. I&amp;#39;m looking for paid or free spots. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I moved here about a week ago and would like to teach my girlfriend the joy of fishing. I'm looking for paid or free spots. ",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v3tm4",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "sethninja13",
"num_comments": 3,
"score": 4,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v3tm4/where_are_the_good_fishing_piers/",
"name": "t3_2v3tm4",
"created": 1423358729,
"url": "http://www.reddit.com/r/Charleston/comments/2v3tm4/where_are_the_good_fishing_piers/",
"author_flair_text": null,
"title": "Where are the good fishing piers?",
"created_utc": 1423329929,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 4
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hello REDDIT - curious where the best place is to get a decent bed frame, headboard, mattress and just all around things to make a nice modern style bedroom for a 30&amp;#39;s something trendy style guy here in charleston?   &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hello REDDIT - curious where the best place is to get a decent bed frame, headboard, mattress and just all around things to make a nice modern style bedroom for a 30's something trendy style guy here in charleston?   ",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v4uh2",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "jkdalrymple",
"num_comments": 12,
"score": 1,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v4uh2/bedroom_decorating_help/",
"name": "t3_2v4uh2",
"created": 1423377361,
"url": "http://www.reddit.com/r/Charleston/comments/2v4uh2/bedroom_decorating_help/",
"author_flair_text": null,
"title": "BEDROOM DECORATING HELP",
"created_utc": 1423348561,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 1
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;m gonna be in Charleston this weekend working on a documentary on craft beer. In addition to beer I really love food trucks. Which ones should I be on the look out for in Charleston?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I'm gonna be in Charleston this weekend working on a documentary on craft beer. In addition to beer I really love food trucks. Which ones should I be on the look out for in Charleston?",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v2rbe",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "camcjohnson",
"num_comments": 34,
"score": 7,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v2rbe/food_trucks_in_charleston/",
"name": "t3_2v2rbe",
"created": 1423326501,
"url": "http://www.reddit.com/r/Charleston/comments/2v2rbe/food_trucks_in_charleston/",
"author_flair_text": null,
"title": "Food Trucks in Charleston",
"created_utc": 1423297701,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 7
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;My wife and I have come to the point where TurboTax isn&amp;#39;t meeting our needs. Any reccs for someone local who can handle complex personal tax situations and who would know the ins and outs of filling jointly or separately?&lt;/p&gt;\n\n&lt;p&gt;The biggest issue is student loan repayment. My wife is doing the 10 year forgiveness program but it&amp;#39;s based off of income. Our two incomes would make it a large monthly payment. Just hers would be easy but we miss out on a ton of tax breaks. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "My wife and I have come to the point where TurboTax isn't meeting our needs. Any reccs for someone local who can handle complex personal tax situations and who would know the ins and outs of filling jointly or separately?\n\nThe biggest issue is student loan repayment. My wife is doing the 10 year forgiveness program but it's based off of income. Our two incomes would make it a large monthly payment. Just hers would be easy but we miss out on a ton of tax breaks. ",
"likes": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "2v09ug",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "89blazer",
"num_comments": 5,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"stickied": false,
"is_self": true,
"permalink": "/r/Charleston/comments/2v09ug/recommendations_for_tax_attorneys_accountants_for/",
"name": "t3_2v09ug",
"created": 1423275175,
"url": "http://www.reddit.com/r/Charleston/comments/2v09ug/recommendations_for_tax_attorneys_accountants_for/",
"author_flair_text": null,
"title": "Recommendations for tax attorneys/ accountants for tax filing",
"created_utc": 1423246375,
"distinguished": null,
"media": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
}
],
"after": "t3_2v09ug",
"before": null
}
};
